### PR TITLE
Feat: Comments + Auth Service

### PR DESCRIPTION
**Pull request by lemohammed**
Whats New?
 - Primary User functionality
- Commenting functionality 
- Microsoft and google sign in 
- Firebase converters - all documents read will automatically convert to class instances
- Auth Service - A class that holds all auth related functions

### CODE REVIEW

**Review by MrClean-1 — APPROVED** [review]
Bro this is straight 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥

**Review by RatikKapoor — APPROVED** [review]
🔥  Let's go!

**Review by rjb75 — APPROVED** [review]
very impressed!

**Review by RatikKapoor — APPROVED** [review]
🚀  Let's go merge!

**Pull request merged**
